---
title: "Simulated Options Trading"
output:
  pdf_document: default
  html_notebook: default
---

```{r setup}
knitr::opts_chunk$set(echo = FALSE,
                      results = "hide")

library(tidyverse)
library(lubridate)
```

# Get Data

## SPX

```{r plot_spx}
holdout_start_date <- ymd("2019-09-13")

spx_weekly <- read_rds("../data/spx_weekly.rds")

spx_weekly %>%
  select(date, holdout, close, pct_return) %>%
  pivot_longer(c(-date, -holdout)) %>%
  ggplot(aes(date, value, color = holdout)) +
  geom_line() +
  geom_vline(xintercept = holdout_start_date, color = "red") +
  facet_grid(name ~ ., scales = "free") +
  scale_x_date(date_breaks = "months", date_labels="%m/%y") +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust=1))
```

## Options

```{r plot_options}
spxw_opt <- read_rds("../data/spxw_opt.rds")

spxw_opt %>%
  filter(quotedate <= ymd("2019-12-20")) %>%
  ggplot(aes(pct_strike, mid_price, color = type)) +
  geom_point() +
  facet_wrap(expiration ~ .) +
  xlab("Option Strike As Pct of Underlying") +
  ylab("Option Price") +
  labs(title = "SPX Friday-Expiring Option Prices Quoted One Week Before Expiration",
              subtitle = "",
              caption = "Only options included in VIX are Considered")
```

# Refit Model for Every Week

```{r one_week_ahead_pred_and_opt_prices}
y_ahead_09_06_19 <- read_rds("../data/y_ahead_09_06_19.rds")


spxw_opt_09_06_19 <- 
  spxw_opt %>%
  filter(quotedate== ymd("2019-09-06"))
  
trap_area <-
  spxw_opt_09_06_19 %>%
  group_by(strike) %>%
  filter(mid_price == max(mid_price)) %>%
  ungroup() %>%
  mutate(width = lead(pct_strike) - pct_strike,
         avg_height = (mid_price + lead(mid_price)) / 2) %>%
  mutate(trap_area = width * avg_height) %>%
  pull(trap_area) %>%
  na.omit() %>%
  sum()

y_ahead_09_06_19 %>%
  ggplot(aes(y_ahead)) +
  geom_histogram(aes(y = trap_area*..density..), binwidth = 0.25) +
  geom_point(aes(pct_strike, mid_price, color = type), data = spxw_opt_09_06_19) +
  xlab("Option Strike As Pct of Underlying") +
  ylab("Option Price") +
  labs(title = "Prices for SPX Options Expiring 9/13/2019 Quoted One Week Before",
              subtitle = "Normalized Histogram of Predicted Returns From SV Model Underlayed",
              caption = "Only options included in VIX are Considered")
```

















