name: 'build' 
on: # rebuild any PRs and main branch changes
  workflow_dispatch: ~
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and run Dev Container task
        uses: devcontainers/ci@v0.3
        env:
          RIINGO_TOKEN: ${{ secrets.riingo_token }}
        with:
          imageName: ghcr.io/pourzanj/homebuying
          cacheFrom: ghcr.io/pourzanj/homebuying
          push: always
          env: |
            RIINGO_TOKEN
          runCmd: |
            R -e "renv::restore()"
            Rscript scripts/daily_fit.R