name: 'daily fit' 
on: # rebuild any PRs and main branch changes
  workflow_dispatch: ~
  schedule:
    # UTC times for 4:40 PM and 4:50 PM Eastern Time
    - cron: "40 21 * * 1-5"
    - cron: "50 21 * * 1-5"
  push:
    branches:
      - master

jobs:
  daily_fit:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Log in to GHCR.io
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GITHUB_ACTOR }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run job in GHCR container
        container:
          image: ghcr.io/pourzanj/homebuying:latest
          env:
            RIINGO_TOKEN: ${{ secrets.riingo_token }}
          run: |
            R -e "renv::restore()"
            Rscript scripts/daily_fit.R