name: 'daily fit'
on: 
  workflow_dispatch: ~
  schedule:
    - cron: "40 19 * * 1-5"
    - cron: "50 19 * * 1-5"
  push:
    branches:
      - master

jobs:
  daily_fit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Docker Image
        run: docker pull ghcr.io/pourzanj/homebuying:latest

      - name: Run daily fit in container
        env:
          RIINGO_TOKEN: ${{ secrets.riingo_token }}
        run: |
          docker run --rm \
            -e RIINGO_TOKEN=${{ secrets.riingo_token }} \
            ghcr.io/pourzanj/homebuying:latest \
            /bin/bash -c "R -e 'renv::restore()'; Rscript scripts/daily_fit.R"
